---
variables:
  CI_BUILD_DOCKER_IMAGE: 10.65.133.229:8091/library/golang:1.20
  CI_BUILD_COMMAND: 'wget http://10.65.133.229:8081/repository/shares/hashicorp/vault/vault_1.16 -O /usr/local/bin/vault && chmod +x /usr/local/bin/vault && make build'
  CI_ARTIFACTS_PATH: bin
include:
  - project: pgs2-rtlabs/devops/ci-cd-templates
    ref: v1
    file: pipelines/common-build.yml
