# MD012/no-multiple-blanks - Multiple consecutive blank lines
MD012:
  # Consecutive blank lines
  maximum: 2

# MD013/line-length - Line length
MD013: false

# MD014/commands-show-output - Dollar signs used before commands without showing output
MD014: false

